### ISSUE TITLE
deprecate deprecated-suicide rule in solium

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/solium-plugin-security#14]
After the merging of `no-selfdestruct-or-suicide` rule in this plugin, that rule becomes redundant.

**Comment by obernardovieira** [comment]
I've found that there's actually some tests failing. Is it tests error or the linter?

**Comment by obernardovieira** [comment]
I'm running on linux mint, please.

The errors are actually tests that fail.
```bash
1) [RULE] no-abstract-func: Rejections
       should reject contracts that use abstract functions:

      AssertionError: expected 0 to be 1
      + expected - actual

      -0
      +1
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/no-abstract-func.js:57:34)

  2) [RULE] no-void-returns: Rejections
       should reject functions that have a void return:

      AssertionError: expected 0 to be 1
      + expected - actual

      -0
      +1
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/no-void-returns.js:48:34)

  3) Checking package.json
       should enforce fixed versions on certain dependencies:
     AssertionError: expected false to be true
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at fixedDevDeps.forEach.fdd (test/packagejson.js:24:59)
      at Array.forEach (<anonymous>)
      at Context.done (test/packagejson.js:23:22)
```
